development:
  adapter: postgresql
  encoding: unicode
  database: timeline-rails_development
  pool: 5
  username: aaron
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: timeline-rails_test
  pool: 5
  username: aaron
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: timeline-rails_production
  pool: 5
  username: aaron
  password:
